
# # all:
# # 	acgmake -dbg -comp=g++-4.1 && \
# # 	acgmake -dbg -comp=g++-4.0 && \
# # 	acgmake -dbg -comp=g++-3.4 && \
# # 	acgmake -dbg -comp=g++-3.3 && \
# # 	acgmake -max -comp=g++-4.1 && \
# # 	acgmake -max -comp=g++-4.0 && \
# # 	acgmake -max -comp=g++-3.4 && \
# # 	acgmake -max -comp=g++-3.3 
	
all:
	acgmake -dbg

clean:
	@acgmake clean



